COMPETITIONS = {
    'AUSTRIA_BUNDESLIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/austria/bundesliga/matches',
    # 'BELARUS_CUP' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    # 'BELARUS_VYSSHAJA_LIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    # 'BELGIUM_FIRST_DIVISION_A' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    'BRAZIL_SERIE_A' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/brazil/serie_a/matches',
    'BULGARIA_FIRST_LEAGUE' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/bulgaria/pfl_1/matches',
    'CHAMPIONS_LEAGUE' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/champions_league/matches',
    'CHINA_SUPER_LEAGUE' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/china/league_one/matches',
    'CZECH_REPUBLIC_1_LIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/czech_republic/first_league/matches',
    'DENMARK_SUPERLIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/denmark/superligaen/matches',
    'ENGLAND_CHAMPIONSHIP' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/england/the_championship/matches',
    'ENGLAND_PREMIER_LEAGUE' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/england/premier_league/matches',
    'EUROPA_LEAGUE' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/europa_league/matches',
    'FINLAND_VEIKKAUSLIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/finland/veikkausliiga/matches',
    # 'FRANCE_LIGUE_ONE' : '',
    'GERMANY_2_BUNDESLIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/germany/2__bundesliga/matches',
    'GERMANY_BUNDESLIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/germany/bundesliga/matches',
    'GERMANY_CUP' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/germany/dfb_pokal/matches',
    #'GREECE_CUP' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    #'GREECE_SUPERLIGA_1' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    'HUNGARY_NB_I' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/hungary/nb_1/matches',
    'ITALY_SERIE_A' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/italy/serie_a/matches',
    'ITALY_SERIE_B' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/italy/serie_b/matches',
    'JAPAN_J1_LEAGUE' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/japan/j1-league/matches',
    #'KOREA_K1_LEAGUE' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    'NORWAY_ELITESERIEN' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/norway/eliteserien/matches',
    'POLISH_CUP' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/poland/puchar_polski/matches',
    'POLISH_EKSTRAKLASA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/poland/ekstraklasa/matches',
    'PORTUGAL_PRIMEIRA_LIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/portugal/primeira_liga/matches',
    'ROMANIA_LIGA_1' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/romania/liga_i/matches',
    'RUSSIA_CUP' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/russia/cup/matches',
    'RUSSIA_PREMIER_LIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/russia/premier_league/matches',
    'SCOTLAND_PREMIERSHIP' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/scotland/scottish_premiership/matches',
    #'SERBIA_SUPERLIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    'SPAIN_PRIMERA_DIVISION' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/spain/la_liga/matches',
    #'SPAIN_SEGUNDA_DIVISION' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    'SWEDEN_ALLSVENSKAN' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/sweden/allsvenskan/matches',
    'SWITZERLAND_SUPERLIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/switzerland/super_league/matches',
    'TURKEY_SUPERLIGA' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football/turkey/super_lig/matches',
    # 'UEFA_NATIONS_LEAGUE_A' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    # 'UEFA_NATIONS_LEAGUE_B' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    # 'UEFA_NATIONS_LEAGUE_C' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    # 'UEFA_NATIONS_LEAGUE_D' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    # 'UEFA_NATIONS_LEAGUE' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    # 'USA_MLS' : 'https://pl.unibet-30.com/sportsbook-feeds/views/filter/football///matches',
    # 'EUROPEAN_CHAMPIONSHIP_WOMENS_HANDBALL': "https://eu-offering.kambicdn.org/offering/v2018/ub/listView/handball/european_championship__w_.json?lang=pl_PL&market=PL&client_id=2&channel_id=1"
    'NBA': 'https://eu-offering.kambicdn.org/offering/v2018/ub/listView/basketball/nba.json?lang=pl_PL&market=PL&client_id=2&channel_id=1&ncid=1609510879167&useCombined=true'

}

MARKETS = {
    # FOOTBALL
    'Penalty Kick awarded' : 'penaltyKick',
    'Total Offsides': 'offsidesTotal',
    'Total Shots': 'shotsTotal',
    'Total Fouls committed' : 'totalFouls',
    'Total Offsides' : 'offsidesTotal',
    'Total Shots on Target' : 'shotsTotalOnTarget',
    'Total Ball possession (%)': 'ballPossesionTotal',
    # Corners
    'Total Corners' : 'cornersTotal',
    'Corners 3-Way Handicap': 'cornersHandicapThreeWay',
    # Cards
    'Total Cards' : 'cardsTotal',
    'Red Card given' : 'redCard',
    'Cards 3-Way Handicap' : 'cardsHandicapThreeWay',
}

